### PR TITLE
Adding isDeprecated field to response

### PR DESCRIPTION
**Pull request by tosan88**

### CODE REVIEW

**Comment by tosan88** [comment]
@andreic92 I don't know why dep changed it, but just to be sure I kept it :man_shrugging: 
Please advise what to do - keep the changes or revert it

**Comment by andreic92** [comment]
Personally, If I have no changes on `Gopkg.toml` I ignore the `.lock` one entirely. So do whatever you know is working best for you 👍

**Comment by khatton-ft** [comment]
@tosan88 Do you have an up-to-date `dep` binary? Those fields were added relatively recently, maybe that's why your copy of the lock file has changed.

**Comment by tosan88** [comment]
I reinstalled `dep`, but lock file remained the same, so I guess this was the case, thanks @khatton-ft :+1:

**Pull request merged**
